/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import java.io.IOException;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

import apiCliente.ClienteApiClient;
import apiCliente.VideojuegoRentadoApiClient;
import modelo.Cliente;
import modelo.VideojuegoRentado;

/**
 *
 * @author DARIO LOPEZ
 */
public class VistaGestionClientes extends javax.swing.JFrame {
	private final VideojuegoRentadoApiClient videojuegoRentadoApiClient;
	private final ClienteApiClient clienteApiClient;
	private String token;

	/**
	 * Creates new form VistaGestionClientes
	 */
	public VistaGestionClientes(String token) {
		initComponents();
		setLocationRelativeTo(this);
		this.token = token;
		this.clienteApiClient = new ClienteApiClient();
		this.videojuegoRentadoApiClient = new VideojuegoRentadoApiClient();
		llenarTablaClientes();

	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		jPanel1 = new javax.swing.JPanel();
		jPanel2 = new javax.swing.JPanel();
		jLabel2 = new javax.swing.JLabel();
		btnListaUsuarios = new javax.swing.JButton();
		btnJuegos = new javax.swing.JButton();
		btnRentas = new javax.swing.JButton();
		btnInventario = new javax.swing.JButton();
		jLabel4 = new javax.swing.JLabel();
		btnMenu = new javax.swing.JButton();
		btnConsolas = new javax.swing.JButton();
		logo = new javax.swing.JLabel();
		jPanel3 = new javax.swing.JPanel();
		jLabel1 = new javax.swing.JLabel();
		jPanel14 = new javax.swing.JPanel();
		jScrollPane2 = new javax.swing.JScrollPane();
		tblClientes = new javax.swing.JTable();
		btnAñadir = new javax.swing.JButton();
		btnEliminar = new javax.swing.JButton();
		btnEditar = new javax.swing.JButton();
		jPanel4 = new javax.swing.JPanel();
		lblImagen = new javax.swing.JLabel();
		txtNombre = new javax.swing.JLabel();
		lblNombre = new javax.swing.JLabel();
		lblCedula = new javax.swing.JLabel();
		lblEdad = new javax.swing.JLabel();
		lblDireccion = new javax.swing.JLabel();
		lblTelefono = new javax.swing.JLabel();
		lblFechaRegistro = new javax.swing.JLabel();
		lblCorreo = new javax.swing.JLabel();
		lblCedulaToFill = new javax.swing.JLabel();
		txtEdad = new javax.swing.JLabel();
		txtDireccion = new javax.swing.JLabel();
		txtTelefono = new javax.swing.JLabel();
		txtFechaRegistro = new javax.swing.JLabel();
		txtCorreo = new javax.swing.JLabel();
		pnlReservas = new javax.swing.JPanel();
		jScrollPane1 = new javax.swing.JScrollPane();
		tblJuegosAlquilados = new javax.swing.JTable();
		jLabel3 = new javax.swing.JLabel();
		txtCedula = new javax.swing.JTextField();
		btnBuscarUsuario = new javax.swing.JButton();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		jPanel1.setBackground(new java.awt.Color(51, 0, 51));

		jPanel2.setBackground(new java.awt.Color(51, 0, 51));

		jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
		jLabel2.setForeground(new java.awt.Color(255, 255, 255));
		jLabel2.setText("Contenido");

		btnListaUsuarios.setBackground(new java.awt.Color(0, 0, 204));
		btnListaUsuarios.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
		btnListaUsuarios.setForeground(new java.awt.Color(255, 255, 255));
		btnListaUsuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Icono User.png"))); // NOI18N
		btnListaUsuarios.setText("Lista de usuarios");
		btnListaUsuarios.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
		btnListaUsuarios.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
		btnListaUsuarios.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
		btnListaUsuarios.setIconTextGap(20);
		btnListaUsuarios.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnListaUsuariosActionPerformed(evt);
			}
		});

		btnJuegos.setBackground(new java.awt.Color(0, 0, 204));
		btnJuegos.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
		btnJuegos.setForeground(new java.awt.Color(255, 255, 255));
		btnJuegos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Icono Control (1).png"))); // NOI18N
		btnJuegos.setText("Juegos");
		btnJuegos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
		btnJuegos.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
		btnJuegos.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
		btnJuegos.setIconTextGap(20);
		btnJuegos.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnJuegosActionPerformed(evt);
			}
		});

		btnRentas.setBackground(new java.awt.Color(0, 0, 204));
		btnRentas.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
		btnRentas.setForeground(new java.awt.Color(255, 255, 255));
		btnRentas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Icono Reloj.png"))); // NOI18N
		btnRentas.setText("Reservas");
		btnRentas.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
		btnRentas.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
		btnRentas.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
		btnRentas.setIconTextGap(20);
		btnRentas.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnRentasActionPerformed(evt);
			}
		});

		btnInventario.setBackground(new java.awt.Color(0, 0, 204));
		btnInventario.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
		btnInventario.setForeground(new java.awt.Color(255, 255, 255));
		btnInventario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Icono Inventario.png"))); // NOI18N
		btnInventario.setText("Inventario");
		btnInventario.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
		btnInventario.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
		btnInventario.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
		btnInventario.setIconTextGap(20);
		btnInventario.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnInventarioActionPerformed(evt);
			}
		});

		jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
		jLabel4.setName(""); // NOI18N

		btnMenu.setBackground(new java.awt.Color(0, 0, 204));
		btnMenu.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
		btnMenu.setForeground(new java.awt.Color(255, 255, 255));
		btnMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Icono home (1).png"))); // NOI18N
		btnMenu.setText("Menu");
		btnMenu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
		btnMenu.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
		btnMenu.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
		btnMenu.setIconTextGap(20);
		btnMenu.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnMenuActionPerformed(evt);
			}
		});

		btnConsolas.setBackground(new java.awt.Color(0, 0, 204));
		btnConsolas.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
		btnConsolas.setForeground(new java.awt.Color(255, 255, 255));
		btnConsolas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/IconoConsola.png"))); // NOI18N
		btnConsolas.setText("Consolas");
		btnConsolas.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
		btnConsolas.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
		btnConsolas.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
		btnConsolas.setIconTextGap(20);
		btnConsolas.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnConsolasActionPerformed(evt);
			}
		});

		logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Logo.png"))); // NOI18N
		logo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
		logo.setName(""); // NOI18N

		javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
		jPanel2.setLayout(jPanel2Layout);
		jPanel2Layout.setHorizontalGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel2Layout.createSequentialGroup().addGroup(jPanel2Layout
						.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(jPanel2Layout.createSequentialGroup().addContainerGap().addGroup(jPanel2Layout
								.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addComponent(btnListaUsuarios, javax.swing.GroupLayout.DEFAULT_SIZE, 200,
										Short.MAX_VALUE)
								.addComponent(btnJuegos, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
								.addComponent(btnRentas, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
								.addComponent(btnInventario, javax.swing.GroupLayout.DEFAULT_SIZE, 200,
										Short.MAX_VALUE)))
						.addGroup(jPanel2Layout.createSequentialGroup().addGap(14, 14, 14).addComponent(jLabel2)
								.addGap(0, 0, Short.MAX_VALUE))
						.addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
								jPanel2Layout.createSequentialGroup().addContainerGap().addComponent(btnMenu,
										javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE))
						.addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
								jPanel2Layout.createSequentialGroup().addContainerGap().addComponent(btnConsolas,
										javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)))
						.addContainerGap())
				.addGroup(jPanel2Layout.createSequentialGroup().addGap(27, 27, 27)
						.addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addComponent(logo).addComponent(jLabel4))
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));
		jPanel2Layout
				.setVerticalGroup(
						jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(jPanel2Layout.createSequentialGroup().addGap(12, 12, 12).addComponent(jLabel4)
										.addGap(15, 15, 15).addComponent(logo).addGap(18, 18, 18).addComponent(jLabel2)
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(btnMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 32,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(btnConsolas, javax.swing.GroupLayout.PREFERRED_SIZE, 32,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(btnJuegos, javax.swing.GroupLayout.PREFERRED_SIZE, 32,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(btnRentas, javax.swing.GroupLayout.PREFERRED_SIZE, 32,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(btnListaUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 32,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(btnInventario, javax.swing.GroupLayout.PREFERRED_SIZE, 32,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addContainerGap(220, Short.MAX_VALUE)));

		jPanel3.setBackground(new java.awt.Color(102, 0, 102));

		jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
		jLabel1.setForeground(new java.awt.Color(255, 255, 255));
		jLabel1.setText("Gestion Usuarios");

		tblClientes.setModel(new javax.swing.table.DefaultTableModel(
				new Object[][] { { "Eduardo", "1145643643", "21", "27/02/2025" }, { null, null, null, null },
						{ null, null, null, null }, { null, null, null, null } },
				new String[] { "Nombre", "Cedula", "Edad", "Registro" }));
		jScrollPane2.setViewportView(tblClientes);

		btnAñadir.setBackground(new java.awt.Color(0, 0, 204));
		btnAñadir.setForeground(new java.awt.Color(255, 255, 255));
		btnAñadir.setText("Añadir");
		btnAñadir.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
		btnAñadir.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnAñadirActionPerformed(evt);
			}
		});

		btnEliminar.setBackground(new java.awt.Color(0, 0, 204));
		btnEliminar.setForeground(new java.awt.Color(255, 255, 255));
		btnEliminar.setText("Eliminar");
		btnEliminar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
		btnEliminar.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				try {
					btnEliminarActionPerformed(evt);
				} catch (Exception e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
			}
		});

		btnEditar.setBackground(new java.awt.Color(0, 0, 204));
		btnEditar.setForeground(new java.awt.Color(255, 255, 255));
		btnEditar.setText("Editar");
		btnEditar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
		btnEditar.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnEditarActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
		jPanel14.setLayout(jPanel14Layout);
		jPanel14Layout
				.setHorizontalGroup(
						jPanel14Layout
								.createParallelGroup(
										javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(jPanel14Layout.createSequentialGroup().addGap(15, 15, 15)
										.addComponent(btnAñadir, javax.swing.GroupLayout.PREFERRED_SIZE, 101,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addGap(18, 18, 18)
										.addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 101,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addGap(18, 18, 18)
										.addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 101,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addContainerGap(24, Short.MAX_VALUE))
								.addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
										jPanel14Layout
												.createSequentialGroup().addContainerGap().addComponent(jScrollPane2,
														javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
												.addContainerGap()));
		jPanel14Layout.setVerticalGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel14Layout.createSequentialGroup()
						.addGap(15, 15, 15)
						.addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 320,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
						.addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(btnAñadir, javax.swing.GroupLayout.PREFERRED_SIZE, 32,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 32,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 32,
										javax.swing.GroupLayout.PREFERRED_SIZE))
						.addGap(150, 150, 150)));

		lblImagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/user.png"))); // NOI18N

		txtNombre.setText("Eduardo Caicedo Pantoja");

		lblNombre.setFont(new java.awt.Font("Dialog", 3, 12)); // NOI18N
		lblNombre.setText("Nombre:");

		lblCedula.setFont(new java.awt.Font("Dialog", 3, 12)); // NOI18N
		lblCedula.setText("Cedula:");

		lblEdad.setFont(new java.awt.Font("Dialog", 3, 12)); // NOI18N
		lblEdad.setText("Edad:");

		lblDireccion.setFont(new java.awt.Font("Dialog", 3, 12)); // NOI18N
		lblDireccion.setText("Direccion:");

		lblTelefono.setFont(new java.awt.Font("Dialog", 3, 12)); // NOI18N
		lblTelefono.setText("Telefono:");

		lblFechaRegistro.setFont(new java.awt.Font("Dialog", 3, 12)); // NOI18N
		lblFechaRegistro.setText("Fecha Registro:");

		lblCorreo.setFont(new java.awt.Font("Dialog", 3, 12)); // NOI18N
		lblCorreo.setText("Correo:");

		lblCedulaToFill.setText("1145643643");

		txtEdad.setText("21");

		txtDireccion.setText("Crra11#22-41");

		txtTelefono.setText("31455434531");

		txtFechaRegistro.setText("27/02/2025");

		txtCorreo.setText("eduardo123@gmail.com");

		pnlReservas.setBorder(javax.swing.BorderFactory.createTitledBorder("Juegos alquilados"));

		tblJuegosAlquilados.setModel(new javax.swing.table.DefaultTableModel(
				new Object[][] { { null, null, null, null, null, null }, { null, null, null, null, null, null },
						{ null, null, null, null, null, null }, { null, null, null, null, null, null } },
				new String[] { "id", "Juego", "Cedula", "Tipo", "Fecha Registro", "Fecha entrega" }));
		jScrollPane1.setViewportView(tblJuegosAlquilados);

		javax.swing.GroupLayout pnlReservasLayout = new javax.swing.GroupLayout(pnlReservas);
		pnlReservas.setLayout(pnlReservasLayout);
		pnlReservasLayout
				.setHorizontalGroup(pnlReservasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(pnlReservasLayout.createSequentialGroup().addContainerGap()
								.addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
								.addContainerGap()));
		pnlReservasLayout
				.setVerticalGroup(pnlReservasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(pnlReservasLayout.createSequentialGroup().addContainerGap()
								.addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
								.addContainerGap()));

		javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
		jPanel4.setLayout(jPanel4Layout);
		jPanel4Layout.setHorizontalGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel4Layout.createSequentialGroup().addContainerGap().addGroup(jPanel4Layout
						.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(jPanel4Layout.createSequentialGroup().addComponent(lblImagen)
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
								.addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
										.addGroup(jPanel4Layout.createSequentialGroup()
												.addGroup(jPanel4Layout
														.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
														.addComponent(lblDireccion).addComponent(lblNombre)
														.addComponent(
																lblCedula)
														.addComponent(lblEdad).addComponent(lblTelefono))
												.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
														javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
												.addGroup(jPanel4Layout
														.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
														.addComponent(txtNombre)
														.addGroup(jPanel4Layout.createSequentialGroup().addGap(1, 1, 1)
																.addGroup(jPanel4Layout.createParallelGroup(
																		javax.swing.GroupLayout.Alignment.LEADING)
																		.addComponent(txtEdad)
																		.addComponent(lblCedulaToFill)
																		.addComponent(txtDireccion)
																		.addComponent(txtTelefono))))
												.addGap(40, 40, 40))
										.addGroup(jPanel4Layout.createSequentialGroup()
												.addGroup(jPanel4Layout
														.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
														.addComponent(lblFechaRegistro).addComponent(lblCorreo))
												.addGap(18, 18, 18)
												.addGroup(jPanel4Layout
														.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(jPanel4Layout.createSequentialGroup()
																.addComponent(txtCorreo)
																.addContainerGap(40, Short.MAX_VALUE))
														.addGroup(jPanel4Layout.createSequentialGroup()
																.addComponent(txtFechaRegistro)
																.addGap(0, 0, Short.MAX_VALUE))))))
						.addComponent(pnlReservas, javax.swing.GroupLayout.DEFAULT_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))));
		jPanel4Layout.setVerticalGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel4Layout.createSequentialGroup().addGap(42, 42, 42)
						.addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(jPanel4Layout.createSequentialGroup().addComponent(lblNombre)
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(lblCedula)
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(lblEdad)
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(lblDireccion)
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(lblTelefono))
								.addComponent(lblImagen)
								.addGroup(jPanel4Layout.createSequentialGroup().addComponent(txtNombre)
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(lblCedulaToFill)
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(txtEdad)
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(txtDireccion)
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 16,
												javax.swing.GroupLayout.PREFERRED_SIZE)))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(lblFechaRegistro).addComponent(txtFechaRegistro))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(lblCorreo).addComponent(txtCorreo))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
						.addComponent(pnlReservas, javax.swing.GroupLayout.DEFAULT_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
						.addGap(25, 25, 25)));

		jLabel3.setText("Usuario");

		txtCedula.setText("Cedula del Usuario");

		btnBuscarUsuario.setText("Buscar");
		btnBuscarUsuario.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				try {
					btnBuscarUsuarioActionPerformed(evt);
				} catch (Exception e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
			}
		});

		javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
		jPanel3.setLayout(jPanel3Layout);
		jPanel3Layout.setHorizontalGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel3Layout.createSequentialGroup().addContainerGap(18, Short.MAX_VALUE)
						.addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(jLabel1))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
						.addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addGroup(jPanel3Layout.createSequentialGroup().addComponent(jLabel3)
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(txtCedula, javax.swing.GroupLayout.PREFERRED_SIZE, 217,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addGap(18, 18, 18).addComponent(btnBuscarUsuario)))
						.addContainerGap()));
		jPanel3Layout.setVerticalGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel3Layout.createSequentialGroup().addContainerGap().addGroup(jPanel3Layout
						.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 51,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout
								.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(txtCedula, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(btnBuscarUsuario).addComponent(jLabel3)))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
						.addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
								.addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
								.addComponent(jPanel14, javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout.setHorizontalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel1Layout.createSequentialGroup()
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
						.addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(0, 0, 0)));
		jPanel1Layout.setVerticalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
						jPanel1Layout.createSequentialGroup().addGap(0, 0, Short.MAX_VALUE).addComponent(jPanel3,
								javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
								javax.swing.GroupLayout.PREFERRED_SIZE))
				.addGroup(jPanel1Layout.createSequentialGroup().addContainerGap()
						.addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup().addGap(0, 0, 0).addComponent(jPanel1,
						javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup().addGap(0, 0, 0).addComponent(jPanel1,
						javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
						.addGap(0, 0, 0)));

		pack();
	}// </editor-fold>//GEN-END:initComponents

	private void btnListaUsuariosActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnListaUsuariosActionPerformed
		// VistaGestionClientes vgc = new VistaGestionClientes();
		// vgc.setVisible(true);
		// this.dispose();
	}// GEN-LAST:event_btnListaUsuariosActionPerformed

	private void btnJuegosActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnJuegosActionPerformed
		VistaGestionDeVideojuegos vj = new VistaGestionDeVideojuegos(token);
		vj.setVisible(true);
		this.setVisible(false);// TODO add your handling code here:
	}// GEN-LAST:event_btnJuegosActionPerformed

	private void btnRentasActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnRentasActionPerformed
		VistaGestionDeReservas vg = new VistaGestionDeReservas(token);
		vg.setVisible(true);
		this.dispose();
	}// GEN-LAST:event_btnRentasActionPerformed

	private void btnInventarioActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnInventarioActionPerformed
		VistaInventario vgi = new VistaInventario(token);
		vgi.setVisible(true);
		this.dispose();
	}// GEN-LAST:event_btnInventarioActionPerformed

	private void btnMenuActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnMenuActionPerformed
		// TODO add your handling code here:
		VistaMenu vl = new VistaMenu(token);
		vl.setVisible(true);
		this.setVisible(false);
	}// GEN-LAST:event_btnMenuActionPerformed

	private void btnConsolasActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnConsolasActionPerformed
		VistaGestionDeConsolas va = new VistaGestionDeConsolas(token);
		va.setVisible(true);
		this.dispose();
	}// GEN-LAST:event_btnConsolasActionPerformed

	private void btnAñadirActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnAñadirActionPerformed
		VistaAñadirCliente va = new VistaAñadirCliente(token);
		va.setVisible(true);
		this.dispose(); // TODO add your handling code here:
	}// GEN-LAST:event_btnAñadirActionPerformed

	private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) throws Exception {// GEN-FIRST:event_btnEliminarActionPerformed
		int filaSeleccionada = tblClientes.getSelectedRow();

		if (filaSeleccionada != -1) {
			Integer idCliente = (Integer) tblClientes.getValueAt(filaSeleccionada, 0);
			int confirmacion = JOptionPane.showConfirmDialog(null,
					"¿Estás seguro que deseas eliminar al cliente con ID " + idCliente + "?", "Confirmar eliminación",
					JOptionPane.YES_NO_OPTION);
			if (confirmacion == JOptionPane.YES_OPTION) {
				this.clienteApiClient.deleteCliente(idCliente, token);
				// Mostrar mensaje de éxito
				JOptionPane.showMessageDialog(null, "Cliente eliminado exitosamente");
				// Recargar la tabla
				llenarTablaClientes();
			}
		} else {
			// Mostrar mensaje si no hay fila seleccionada
			JOptionPane.showMessageDialog(null, "Se debe seleccionar un cliente de la tabla para poderlo eliminar");
		}
	}// GEN-LAST:event_btnEliminarActionPerformed

	private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnEditarActionPerformed
		Integer filaSeleccionada = tblClientes.getSelectedRow();
		if (filaSeleccionada != -1) {
			Integer idCliente = (Integer) tblClientes.getValueAt(filaSeleccionada, 0);
			int confirmacion = JOptionPane.showConfirmDialog(null,
					"¿Estás seguro que deseas editar al cliente con ID " + idCliente + "?", "Confirmar editar",
					JOptionPane.YES_NO_OPTION);
			if (confirmacion == JOptionPane.YES_OPTION) {
				VistaEditarCliente vs = new VistaEditarCliente(idCliente, token);
				vs.setVisible(true);
				this.dispose();
				llenarTablaClientes();
			}
		} else {

			JOptionPane.showMessageDialog(null, "Se debe seleccionar un cliente de la tabla para poderlo eliminar");
		}
	}// GEN-LAST:event_btnEditarActionPerformed

	private void btnBuscarUsuarioActionPerformed(java.awt.event.ActionEvent evt) throws Exception {// GEN-FIRST:event_btnBuscarUsuarioActionPerformed
		Cliente clienteBuscado = clienteApiClient.buscarClientePorCedula(txtCedula.getText(), token);
		if (clienteBuscado != null) {
			llenarDatosCliente(clienteBuscado);
			llenarTablaJuegosAlquilados(clienteBuscado);
		} else {
			throw new Exception("No se encontro el cliente");
		}
	}// GEN-LAST:event_btnBuscarUsuarioActionPerformed

	private void llenarDatosCliente(Cliente cliente) {
		txtNombre.setText(cliente.getNombre());
		lblCedulaToFill.setText(cliente.getCedula());
		txtEdad.setText(String.valueOf(cliente.getEdad()));
		txtDireccion.setText(cliente.getDireccion());
		txtTelefono.setText(cliente.getTelefono());
		txtCorreo.setText(cliente.getEmail());
		txtFechaRegistro.setText(cliente.getFechaRegistro().toString());
	}

	private void llenarTablaClientes() {
		DefaultTableModel model = new DefaultTableModel();
		model.setColumnIdentifiers(
				new Object[] { "id", "Cedula", "Nombre", "Edad", "Dirrecion", "Telefono", "correo", "Registro" });

		List<Cliente> aux = clienteApiClient.listarCliente(token);
		for (Cliente cliente : aux) {
			model.addRow(new Object[] { cliente.getId(), cliente.getCedula(), cliente.getNombre(), cliente.getEdad(),
					cliente.getDireccion(), cliente.getTelefono(), cliente.getEmail(),
					cliente.getFechaRegistro().toString()

			});
		}
		tblClientes.setModel(model);
	}

	public void llenarTablaJuegosAlquilados(Cliente clienteBuscando) {
        try {
            DefaultTableModel model = new DefaultTableModel();
            model.setColumnIdentifiers(new Object[]{"id", "id cliente", "Juego", "Fecha Alquiler", "Fecha Devolucion"});
            List<VideojuegoRentado> aux = this.videojuegoRentadoApiClient.buscarVideoJuegosRentadosDelCliente(clienteBuscando.getId(), token);
            if (aux == null || aux.isEmpty()) {
                JOptionPane.showMessageDialog(this, "No se encontraron juegos alquilados para el cliente con cedula: " + clienteBuscando.getCedula());
                tblJuegosAlquilados.setModel(model);
                return;
            }
            for (VideojuegoRentado videojuego : aux) {

                model.addRow(new Object[]{
                    videojuego != null ? videojuego.getId() : "NULL",
                    videojuego != null ? videojuego.getIdCliente() : "NULL",
                    videojuego != null ? videojuego.getIdVideojuego() : "NULL",
                    videojuego != null ? videojuego.getFechaAlquiler() : "NULL",
                    videojuego != null ? videojuego.getFechaDevolucion() : "NULL"
                });

            }
            tblJuegosAlquilados.setModel(model);
        } catch (Exception e) {
            System.out.println("ERROR: " + e.getMessage());
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
        }
    }

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		// <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
		// (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the default
		 * look and feel. For details see
		 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(VistaGestionClientes.class.getName()).log(java.util.logging.Level.SEVERE,
					null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(VistaGestionClientes.class.getName()).log(java.util.logging.Level.SEVERE,
					null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(VistaGestionClientes.class.getName()).log(java.util.logging.Level.SEVERE,
					null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(VistaGestionClientes.class.getName()).log(java.util.logging.Level.SEVERE,
					null, ex);
		}
		// </editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new VistaGestionClientes(null).setVisible(true);
			}
		});
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton btnAñadir;
	private javax.swing.JButton btnBuscarUsuario;
	private javax.swing.JButton btnConsolas;
	private javax.swing.JButton btnEditar;
	private javax.swing.JButton btnEliminar;
	private javax.swing.JButton btnInventario;
	private javax.swing.JButton btnJuegos;
	private javax.swing.JButton btnListaUsuarios;
	private javax.swing.JButton btnMenu;
	private javax.swing.JButton btnRentas;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JPanel jPanel14;
	private javax.swing.JPanel jPanel2;
	private javax.swing.JPanel jPanel3;
	private javax.swing.JPanel jPanel4;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JScrollPane jScrollPane2;
	private javax.swing.JLabel lblCedula;
	private javax.swing.JLabel lblCedulaToFill;
	private javax.swing.JLabel lblCorreo;
	private javax.swing.JLabel lblDireccion;
	private javax.swing.JLabel lblEdad;
	private javax.swing.JLabel lblFechaRegistro;
	private javax.swing.JLabel lblImagen;
	private javax.swing.JLabel lblNombre;
	private javax.swing.JLabel lblTelefono;
	private javax.swing.JLabel logo;
	private javax.swing.JPanel pnlReservas;
	private javax.swing.JTable tblClientes;
	private javax.swing.JTable tblJuegosAlquilados;
	private javax.swing.JTextField txtCedula;
	private javax.swing.JLabel txtCorreo;
	private javax.swing.JLabel txtDireccion;
	private javax.swing.JLabel txtEdad;
	private javax.swing.JLabel txtFechaRegistro;
	private javax.swing.JLabel txtNombre;
	private javax.swing.JLabel txtTelefono;
	// End of variables declaration//GEN-END:variables
}
